/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2024-04-04 11:00:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/12월%20전자정부기반%20e커머스%20융합%20sw개발자%20박정은/5.%20프레임워크%20융합%20SW%20개발/workspace-spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/day72/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1710931300356L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("    <meta name=\"description\" content=\"\" />\r\n");
      out.write("    <meta name=\"author\" content=\"\" />\r\n");
      out.write("    <title>Money For Travel - 여행지를 결정하신 분!</title>\r\n");
      out.write("    <!-- Favicon-->\r\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"assets/favicon.ico\" />\r\n");
      out.write("    <!-- Bootstrap icons-->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\" rel=\"stylesheet\"\r\n");
      out.write("        type=\"text/css\" />\r\n");
      out.write("    <!-- Google fonts-->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic\" rel=\"stylesheet\"\r\n");
      out.write("        type=\"text/css\" />\r\n");
      out.write("    <!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("    <link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <!-- Font Awesome icons (free version)-->\r\n");
      out.write("    <script src=\"https://use.fontawesome.com/releases/v6.3.0/js/all.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"js/scripts.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Masthead-->\r\n");
      out.write("    <header class=\"masthead\">\r\n");
      out.write("        <div class=\"container position-relative\">\r\n");
      out.write("            <div class=\"row justify-content-center\">\r\n");
      out.write("                <div class=\"col-xl-6\">\r\n");
      out.write("                    <div class=\"text-center text-white\">\r\n");
      out.write("                        <!-- 페이지 제목-->\r\n");
      out.write("                        <h1 class=\"mb-5\">여행지를 선택하여 주세요~!</h1>\r\n");
      out.write("                        <!-- 확인 버튼만 있는 양식-->\r\n");
      out.write("                        <form class=\"form-subscribe\" id=\"contactForm\" onsubmit=\"submitForm(event)\">\r\n");
      out.write("                            <div class=\"col-auto\">\r\n");
      out.write("                                <button class=\"scroll-button btn btn-primary\" onclick=\"scrollToFeature()\">확인</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <div id=\"result\" class=\"mt-3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Icons Grid-->\r\n");
      out.write("    <section class=\"features-icons bg-light text-center\" id=\"fu\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                        <i class=\"fa-solid fa-location-dot\" style=\"color: #005eff;\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3>지역 선택</h3>\r\n");
      out.write("                    <p class=\"lead mb-0\">여행을 가고자 하는 지역을 선택해주세요!<br></p>\r\n");
      out.write("                    <select style=\"font-size: 20px\">\r\n");
      out.write("                        <option>어디 지역에 여행을 갈지 선택해주세요\r\n");
      out.write("                        <option id=\"areagangwon\">강원도\r\n");
      out.write("                        <option id=\"areagyeonggi\">경기도\r\n");
      out.write("                        <option id=\"areagyeongnam\">경상남도\r\n");
      out.write("                        <option id=\"areagyeongbuk\">경상북도\r\n");
      out.write("                        <option id=\"areagwangju\">광주광역시\r\n");
      out.write("                        <option id=\"areadaegu\">대구광역시\r\n");
      out.write("                        <option id=\"areadaejeon\">대전광역시\r\n");
      out.write("                        <option id=\"areabusan\">부산광역시\r\n");
      out.write("                        <option id=\"areaseoul\">서울특별시\r\n");
      out.write("                        <option id=\"areaulsan\">울산광역시\r\n");
      out.write("                        <option id=\"areaincheon\">인천광역시\r\n");
      out.write("                        <option id=\"areajeunnam\">전라남도\r\n");
      out.write("                        <option id=\"areajeunbuk\">전라북도\r\n");
      out.write("                        <option id=\"areajeju\">제주특별자치도\r\n");
      out.write("                        <option id=\"areachungnam\">충청남도</option>\r\n");
      out.write("                        <option id=\"areachungbuk\">충청북도</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-7\">\r\n");
      out.write("                <div class=\"features-icons-item mx-auto mb-0 mb-lg-3\">\r\n");
      out.write("                    <div class=\"col-lg-7\">\r\n");
      out.write("                        <i class=\"fa-solid fa-map-location-dot\" style=\"color: #0d6efd;\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3>목적 여부</h3>\r\n");
      out.write("                    <p class=\"lead mb-0\">여행 목적을 선택해 주세요!</p>\r\n");
      out.write("                    <form id=\"choicesForm\" style=\"font-size: 20px; margin-top: 3px;\">\r\n");
      out.write("                        <label><input type=\"checkbox\" name=\"choices\" value=\"미정\" id=\"notpurpose\"> 미정</label>\r\n");
      out.write("                        <label><input type=\"checkbox\" name=\"choices\" value=\"골프\" id=\"golf\"> 골프</label>\r\n");
      out.write("                        <label><input type=\"checkbox\" name=\"choices\" value=\"스키\" id=\"ski\"> 스키</label>\r\n");
      out.write("                        <label><input type=\"checkbox\" name=\"choices\" value=\"관광유원\" id=\"amuse\"> 관광유원</label>\r\n");
      out.write("                        <label><input type=\"checkbox\" name=\"choices\" value=\"기타레저\" id=\"leisure\"> 기타레저</label>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4\">\r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                    <i class=\"fa-solid fa-calendar-days\" style=\"color: #0d6efd;\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3>여행 월</h3>\r\n");
      out.write("                <p class=\"lead mb-0\">여행을 가고자 하는 월을 선택해주세요!<br>(1월~12월)</p>\r\n");
      out.write("                <select style=\"font-size: 20px\">\r\n");
      out.write("                    <option>몇월달에 여행을 가실지 선택해주세요\r\n");
      out.write("                    <option id=\"jan\">1월</option>\r\n");
      out.write("                    <option id=\"feb\">2월</option>\r\n");
      out.write("                    <option id=\"mar\">3월</option>\r\n");
      out.write("                    <option id=\"apr\">4월</option>\r\n");
      out.write("                    <option id=\"may\">5월</option>\r\n");
      out.write("                    <option id=\"jun\">6월</option>\r\n");
      out.write("                    <option id=\"jul\">7월</option>\r\n");
      out.write("                    <option id=\"jan\">8월</option>\r\n");
      out.write("                    <option id=\"sep\">9월</option>\r\n");
      out.write("                    <option id=\"oct\">10월</option>\r\n");
      out.write("                    <option id=\"nov\">11월</option>\r\n");
      out.write("                    <option id=\"dec\">12월</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-4\">\r\n");
      out.write("            <div class=\"col-lg-4\">\r\n");
      out.write("                <i class=\"fa-solid fa-bed\" style=\"color: #0d6efd;\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3>숙박 여부</h3>\r\n");
      out.write("            <p class=\"lead mb-0\">숙박 선택 가능일은 0일에서 <br>최대 5일까지 입니다!</p>\r\n");
      out.write("            <select style=\"font-size: 20px\">\r\n");
      out.write("                <option>숙박일을 선택해 주세요</option>\r\n");
      out.write("                <option>미정</option>\r\n");
      out.write("                <option id=\"zeronight\">0일</option>\r\n");
      out.write("                <option id=\"onenight\">1일</option>\r\n");
      out.write("                <option id=\"twonight\">2일</option>\r\n");
      out.write("                <option id=\"threenight\">3일</option>\r\n");
      out.write("                <option id=\"fournight\">4일</option>\r\n");
      out.write("                <option id=\"fivenight\">5일</option>\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-4\">\r\n");
      out.write("            <div class=\"features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3\">\r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                    <i class=\"fa-solid fa-bowl-food\" style=\"color: #0d6efd;\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3>식음료 여부</h3>\r\n");
      out.write("                <p class=\"lead mb-0\">식사를 몇 끼 하실지 선택해 주세요!</p>\r\n");
      out.write("                <select style=\"font-size: 20px\">\r\n");
      out.write("                    <option>식사를 몇 끼 하실지 선택해 주세요</option>\r\n");
      out.write("                    <option id=\"notmeal\">미정</option>\r\n");
      out.write("                    <option id=\"zeromeal\">0끼</option>\r\n");
      out.write("                    <option id=\"onemeal\">1끼</option>\r\n");
      out.write("                    <option id=\"twomeal\">2끼</option>\r\n");
      out.write("                    <option id=\"threemeal\">3끼</option>\r\n");
      out.write("                    <option id=\"fourmeal\">4끼</option>\r\n");
      out.write("                    <option id=\"fivemeal\">5끼</option>\r\n");
      out.write("                    <option id=\"sixmeal\">6끼</option>\r\n");
      out.write("                    <option id=\"sevenmeal\">7끼</option>\r\n");
      out.write("                    <option id=\"eightmeal\">8끼</option>\r\n");
      out.write("                    <option id=\"ninemeal\">9끼</option>\r\n");
      out.write("                    <option id=\"tenmeal\">10끼</option>\r\n");
      out.write("                    <option id=\"elevenmeal\">11끼</option>\r\n");
      out.write("                    <option id=\"notmeal\">12끼</option>\r\n");
      out.write("                    <option id=\"notmeal\">13끼</option>\r\n");
      out.write("                    <option id=\"notmeal\">14끼</option>\r\n");
      out.write("                    <option id=\"notmeal\">15끼</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("            <div class=\"dis\" style=\"font-size: 20px; margin-top: 23px;\">\r\n");
      out.write("        <a class=\"btn btn-primary btn-lg px-4 me-sm-3\" href=\"#show\">최종 제출</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Testimonials section-->\r\n");
      out.write("    <section class=\"py-5 border-bottom\">\r\n");
      out.write("        <div class=\"container px-5 my-5 px-5\">\r\n");
      out.write("            <div class=\"text-center mb-7\">\r\n");
      out.write("                <h2 class=\"fw-bolder\">예상되는 예산</h2>\r\n");
      out.write("                <p class=\"lead mb-0\">위에서 선택한 것을 통해 예측한 여행예산입니다. </p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row gx-5 justify-content-center\">\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <!-- Testimonial 2-->\r\n");
      out.write("                    <div class=\"card\" id=\"show\">\r\n");
      out.write("                        <div class=\"card-body p-4\">\r\n");
      out.write("                            <div class=\"d-flex\">\r\n");
      out.write("                                <div class=\"ms-4-1\">\r\n");
      out.write("                                    <p class=\"mb-1\">예상되는 여행예산은</p>\r\n");
      out.write("                                    <label for=\"numberInput\">숫자를 입력하세요:</label>\r\n");
      out.write("                                    <input type=\"number\" id=\"numberInput\" onchange=\"showNumber()\">\r\n");
      out.write("                                    <p><span class=\"out\" id=\"output\"></span>원 입니다.</p>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Core theme JS-->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.startbootstrap.com/sb-forms-latest.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/index.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("cpath");
      // /WEB-INF/views/index.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/index.jsp(4,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
